version: '3'
services:
  postgres:
        image: postgres:10.5
        restart: always
        environment:
           - POSTGRES_USER=customer
           - POSTGRES_PASSWORD=password
           - POSTGRES_DB=devicewarehouse
        ports:
           - "5432:5432"
        volumes: 
          - ./docker/postgres-data:/var/lib/postgresql/data
  app:
        build: .
        environment:
           - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devicewarehouse
        ports:
          - "8080:8080"
        depends_on:
          - postgres